[tool.black]
line-length = 100
target-version = ["py38"]


[tool.isort]
profile = "black"
line_length = 100
known_first_party = ["victoria_terminal"]


[tool.flake8]
max-line-length = 100
extend-ignore = ["E203", "W503"]
