name: Build and Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Run test suite
        run: |
          python tests/test_victoria.py
          python tests/test_non_interactive.py

  build:
    needs: test
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv
      - name: Install Inno Setup
        if: matrix.os == 'windows-latest'
        run: |
          choco install -y innosetup
      - name: Build Windows executable
        if: matrix.os == 'windows-latest'
        shell: cmd
        run: scripts\package_win.bat
      - name: Upload build version
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: build-version
          path: VERSION
          if-no-files-found: error
      - name: Build macOS app
        if: matrix.os == 'macos-latest'
        run: |
          bash scripts/package_mac.sh
      - name: Upload Windows artifact
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: victoria-windows
          path: |
            dist/Victoria.exe
            dist/VictoriaSetup.exe
          if-no-files-found: error
      - name: Upload macOS artifact
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: victoria-macos
          path: Victoria.app.zip
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build version
        uses: actions/download-artifact@v4
        with:
          name: build-version
          path: release
      - name: Read build version
        run: |
          VERSION=$(tr -d '\r\n' < release/VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          rm release/VERSION
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: victoria-windows
          path: release
      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: victoria-macos
          path: release
      - name: Include dependencies
        run: |
          cp dependencies/install_prerequisites_* release/
          cp dependencies/set_env_* release/
      - name: Rename artifacts with version
        run: |
          mv release/Victoria.exe "release/Victoria-${VERSION}.exe"
          mv release/VictoriaSetup.exe "release/Victoria-${VERSION}-Setup.exe"
          mv release/Victoria.app.zip "release/Victoria-${VERSION}.app.zip"
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          name: Victoria v${{ env.VERSION }}
          generate_release_notes: true
          files: release/*
